/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ocr_OCRMain */

#ifndef _Included_com_ocr_OCRMain
#define _Included_com_ocr_OCRMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ocr_OCRMain
 * Method:    initAndroidOCR
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ocr_OCRMain_initAndroidOCR
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ocr_OCRMain
 * Method:    createBitmapColors
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ocr_OCRMain_createBitmapColors
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ocr_OCRMain
 * Method:    processBitmapOverlay
 * Signature: ([BLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_ocr_OCRMain_processBitmapOverlay
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     com_ocr_OCRMain
 * Method:    getImageText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ocr_OCRMain_getImageText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
